# TODO: must implement
---
GET http://localhost:3000/auth/login

---
GET http://localhost:3000/auth/signup

---
GET http://localhost:3000/auth/refresh

---
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31"
}
