# https://taskfile.dev
version: '3'
tasks:
  init:
    desc: Install some important commands and tools
    cmds:
      - pnpm install
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/vektra/mockery/v2@latest
      - go mod tidy
  assets:
    desc: Build the assets
    cmds:
      - echo "Building assets"
  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...
      # - swag init -g ./cmd/api/main.go
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - go run ./cmd/app/...
  dev:
    desc: Develop the api
    deps:
      - assets
      - generate
    cmds:
      - air -c .air.api.toml
  build-api:
    desc: build the api
    deps:
      - assets
      - generate
    cmds:
      # - go build -o ./bin/api ./cmd/api/...
      - go build -o=../../dist/apps/its-battistar-be-go/ ./cmd/server
  serve-api:
    desc: Build and serve the api
    deps:
      - build-api
    cmds:
      # - ./bin/api
      - ../../dist/apps/its-battistar-be-go/server
  test:
    desc: Run the tests
    cmds:
      - go test ./...
  release:
    desc: Release the application
    cmds:
      - goreleaser release --rm-dist
