# https://taskfile.dev
version: '3'
tasks:
  init:
    desc: Install some important commands and tools
    cmds:
      - pnpm install
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/vektra/mockery/v2@latest
      - go mod tidy
  # assets:
  #   desc: Build the assets
  #   cmds:
  #     - tailwindcss -i ./web/vite/tailwind.css -o ./web/dist/styles.css
  # TODO: for now i manually have to import the hashed files
  assets:
    desc: Build the assets
    cmds:
      - pnpm build
  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...
      - swag init -g ./cmd/api/main.go
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - go run ./cmd/app/...
  dev-app:
    desc: Develop the application
    deps:
      - assets
      - generate
    cmds:
      - air -c .air.app.toml
  dev:
    desc: Develop the api
    # deps:
    #   - assets
    #   - generate
    cmds:
      - air -c .air.toml
  build-app:
    desc: build the application
    deps:
      - assets
      - generate
    cmds:
      - go build -o ./bin/app ./cmd/app/...
  build-api:
    desc: build the api
    deps:
      - assets
      - generate
    cmds:
      - go build -o ./bin/api ./cmd/api/...
  serve-app:
    desc: Build and serve the application
    deps:
      - assets
      - generate
      - build-app
    cmds:
      - ./bin/app
  serve-api:
    desc: Build and serve the api
    deps:
      - assets
      - generate
      - build-api
    cmds:
      - ./bin/api
  test:
    desc: Run the tests
    cmds:
      - go test ./...
  release:
    desc: Release the application
    cmds:
      - goreleaser release --rm-dist
